name: monero_jsonrpc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_rpc_client: ^1.0.0
  ninja_ed25519: ^1.0.0
  sha3: ^0.2.0
  bs58check: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
